import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

const files = [
  "src/js/data/content.js",
  "src/js/modules/scramble.js",
  "src/js/modules/magneticType.js",
  "src/js/modules/aurora.js",
  "src/js/modules/fx.js",
  "src/js/modules/cursor.js",
  "src/js/modules/orbit.js",
  "src/js/modules/overlays.js",
  "src/js/main.js",
];

function transform(code, file) {
  return code
    .replace(/^\s*import\s+.+?;\s*$/gm, "")
    .replace(/export\s+async\s+function/g, "async function")
    .replace(/export\s+function/g, "function")
    .replace(/export\s+const/g, "const")
    .replace(/export\s+\{[\s\S]*?\};?/g, "")
    .replace(/\r\n/g, "\n");
}

let bundle = `/* Auto-generated by build.mjs — do not edit by hand */\n`;
bundle += `(function () {\n  "use strict";\n`;

for (const rel of files) {
  const abs = path.join(root, rel);
  const code = transform(fs.readFileSync(abs, "utf8"), rel);
  bundle += `\n  // ---- ${rel} ----\n`;
  bundle += code
    .split("\n")
    .map((line) => (line.length ? `  ${line}` : line))
    .join("\n");
  bundle += "\n";
}

bundle += `\n})();\n`;

const outPath = path.join(root, "src/js/app.bundle.js");
fs.writeFileSync(outPath, bundle, "utf8");
console.log(`Built ${path.relative(root, outPath)} (${bundle.length} bytes)`);
